### ISSUE TITLE
import latest code of ContextJS from lively kernel / babelsberg 

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/ContextJS#1]
and get it running stand alone

**Comment by JensLincke** [comment]
Import from these sources...
- https://github.com/LivelyKernel/LivelyKernel/tree/master/core/cop
- https://github.com/babelsberg/babelsberg-js/tree/master/cop
- https://github.com/mischkew/CopReact/tree/master/src/lib/cop

**Comment by JensLincke** [comment]
@LanDinh @j4yk

**Comment by j4yk** [comment]
I suppose we did that some weeks ago. :-)
