### ISSUE TITLE
Review Layers.js module exports

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#10]
Currently, the old `cop` object is the default export, while there are also some named exports like the Layer class. Basically, I just exported things in such a way that the changes to the existing unit tests are minimal...

Since the cop object is only the old means of scoping, when ES6 modules were not a thing, we could replace that by lots of named exports which can then be imported like this: `import * as cop from '.../Layers'` if that were preferable. It would also allow to only import layerClass, layerObject, or Layer if you need them. What would be a good default export then? Or we keep both ways, having the cop object as a default export, but all individual "global" cop functions primarily as named exports. That would mean, the cop object is only assembled at the end of the module like this `export default { layerClass: layerClass, layerObject: layerObject, ... }`.

**Comment by onsetsu** [comment]
I would prefer not having a `cop` object as default export, but export individual named functions. If one wants to use `cop` in the old-fashion way `import * as cop` should work.
