### ISSUE TITLE
import * from ".../cop" should make core functions available

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#19]
Writing `import * from ".../cop"` should make the module "cop-aware", so you have `proceed`, `withLayers`, `withoutLayers` and a method to access a layer (`layer`?, currently `create`) available at module scope.

**Comment by LanDinh** [comment]
Done! `import ".../contextjs"` now imports proceed, withLayers, wihtoutLayers and layer. If more functionality is needed, the user needs to `import * as cop from ".../layer"` as well.
