### ISSUE TITLE
Make cop importable as import "contextjs"

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#22]
Think of a solution so the import statement looks nice in apps using ContetxJS. package.json and bower in combination with an index.js might help.

That "main" file should export functions as indicated in #19, while more implementation details should be importable as they currently are, by importing directly from Layers.js.

**Comment by LanDinh** [comment]
Should be fixed with pull request #36

**Comment by j4yk** [comment]
Turnaround: don't do side-effects by default, so make the entry module import side-effect free again. And usually you want to do `import { proceed, ... } from 'contextjs'` again.

**Comment by LanDinh** [comment]
Done with merge #36
