### ISSUE TITLE
Deprecate layerClass, layerObject functions

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#24]
Currently there are two ways to define partial state or behavior:

```
cop.layerObject(theLayer, theObject, thePartials)`
```

and

```
theLayer.refineObject(theObject, thePartials)`
```

...and their respective companions `layerClass` and `refineClass`.

I think the latter reads better. Should we therefore deprecate the other syntax?

**Comment by onsetsu** [comment]
Yes, we can simply deprecate `layerObject` and `layerClass`.
