### ISSUE TITLE
Transpile code to ES5 before publishing

### ISSUE THREAD

**Issue by LanDinh** [LivelyKernel/ContextJS#32]
As ES6 isn't supported natively, transpilation to ES5 is needed before publishing.

**Comment by LanDinh** [comment]
Done by #40 .
Problems: When installing from the git repo instead of the npm server (as done while it is not published yet), dependencies to babel and browserify are needed for transpilation - dirty fix: check in transpiled code into the repository.

Needs to be discussed in the next meeting.

**Comment by j4yk** [comment]
In last weeks meeting, it was proposed to check in the transpiled sources if there is no cleaner way. I found another discussion related to the prepublish script and git dependencies: npm/npm#3055 basically, people want npm install git://... to behave as if that repo was cloned and then `cd ... && npm install`-ed, so devDependencies are downloaded, prepublish is executed and the sources are transpiled. [One participant provied](https://github.com/npm/npm/issues/3055#issuecomment-158679721) the following as a workaround: https://github.com/lzrski/npm-git-install This can be used by our "clients" to add ContextJS on GitHub as a dependency if they are not satisfied with the published version. So all we would have to do is refer to npm/npm#3055 and this npm-git-install thing in our Readme for the time being.
