### ISSUE TITLE
add reinstall method to layer

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/ContextJS#33]
layers should be able to make methods in their target object layer aware again after they have changed.

**Comment by j4yk** [comment]
I think we cannot handle the case when the object that contains the layered properties is replaced. For example, if you evaluate `class C {}` two times in Lively, you get two completely separate C functions each time. A layer cannot know that the old prototype with layered properties has something in common with the new prototype. If we talk about a function (subsuming classes), it might have a name if we are lucky. But then we still miss the scope in which that name is (or might still be) bound to the function.

We could, however, re-layer replaced properties on the same object. But does that solve your use case?

**Comment by j4yk** [comment]
We can assume that lively will try to modify the existing objects instead of replacing them when a module is reloaded.
