### ISSUE TITLE
Add installation notes to the readme

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#44]
Particularly about using https://github.com/lzrski/npm-git-install for the time being if depending directly on the GitHub repository.

Probably the readme should also include some information about the transpilation to justify the above.

**Comment by j4yk** [comment]
Did that and also added a paragraph about what COP is anyway. Can somebody please review that for accurateness and comprehensibility, @LanDinh, @JensLincke, @onsetsu? Or just revert the commit if you think it is not neccessary. Please close this issue after a review.

**Comment by onsetsu** [comment]
Looks okay.
