### ISSUE TITLE
Create publish-ready package.json and bower.json files

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/ContextJS#9]
Make sure that
- the license is right (include a LICENSE or COPYING file by the way)
- the contact info is up-to-date
- the dependencies are accurate
- the entry-points (main files, probably) are defined correctly
- the version number should probably start at 2.0.0 (1.x being the Lively-tied non-ES6 ContextJS)

We could build a simple test app, which requires ContextJS and should be running properly after invoking npm install or bower install.

**Comment by j4yk** [comment]
Should we rename Layers.js to contextjs.js or context.js or at least introduce that as an entry point? In the latter case, it would reexport most of the stuff from Layers.js and, in the future, possibly more from other modules.

**Comment by j4yk** [comment]
Note #22

**Comment by LanDinh** [comment]
package.json has been adjusted, contact information still needs to be entered as there can only be one author (probably @JensLincke ? ) and several contributers, I also didn't want to publish contact information without getting approval first ( @j4yk )

Code needs to be transpiled to ES5 first before publishing, see #32 .

**Comment by j4yk** [comment]
I am (or will be) fine with putting my name on this ;-) But there are several more important contributors (GitHub will show you each of them), those who actually came up with the implementation (rather than shuffling code around and renaming functions).

The "one and only" author could also be(come) the HPI Software Architecture Group or that department where Lively3 was developed (and ContextJS by the way). Let's talk to @JensLincke for the proper history.

**Comment by LanDinh** [comment]
`package.json` should have been merged with #31 , `bower.json` is created with #37

**Comment by LanDinh** [comment]
Already merged
